apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: grpc-client
  namespace: ecarx-app
spec:
  host: grpc-client
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grpc-client
  namespace: ecarx-app
spec:
  hosts:
  - grpc-client
  http:
    - route:
      - destination:
          host: grpc-client
          subset: v1
      retries:
        attempts: 3
        perTryTimeout: 2s
