apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: message-center
  namespace: ecarx-app
spec:
  host: message-center
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: message-center
  namespace: ecarx-app
spec:
  hosts:
  - message-center
  http:
  - match:
    - uri:
        prefix: /protected
    route:
    - destination:
        host: message-center
        subset: v2
